### ISSUE TITLE
The sandbox is not in sync with the Podfile.lock

### ISSUE THREAD

**Issue by petercv** [jcampbell05/cocoapods-deploy#2]
Tried to use cocoapods-deploy today (great idea btw!) and although initially it looked that everything was working fine (pods were being deployed/installed etc.) when I tried to build the project I ran into the following error:

```
Running script 'Check Pods Manifest.lock'
Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

It seems no Manifest.lock file is being generated when using the deploy command and this confused Cocoapods during the build process.

**Comment by jcampbell05** [comment]
@petercv I've just ran it and you're right! Thanks for noticing this :) I'll push a fix out fairly quickly.

**Comment by jcampbell05** [comment]
@petercv I've just released `0.0.2` which fixes the `Manifest` not being generated. Could you try it out and let me know if it works :)

**Comment by petercv** [comment]
Great! Thanks for the quick response! I ran into another issue for which I will make a separate issue. Tried to install 0.0.2, but it seems the gem is not available yet, will try it as soon as it is available.

**Comment by jcampbell05** [comment]
@petercv It should be available now for some reason it didn't upload but it should be there. Great that will be a big help trying to find these extra cases.

**Comment by petercv** [comment]
Just installed it, works like a charm!
