### ISSUE TITLE
Compatibility with Cocoapods 1.0

### ISSUE THREAD

**Issue by petercv** [jcampbell05/cocoapods-deploy#6]
The plug-in doesn't seem compatible with Cocoapods 1.0. Any plans?

**Comment by jcampbell05** [comment]
@petercv Hey, yes. I would love to get this working with 1.0, if you like you could submit a PR. But I'll try and get around to this when I can.

**Comment by jcampbell05** [comment]
@petercv  Do you have a copy of the error ?

**Comment by petercv** [comment]
20:
21: ---------------------------------------------
22: Error loading the plugin `cocoapods-deploy-0.0.9`.
23:
24: TypeError - wrong argument type Class (expected Module)
25: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods-deploy/command/deploy.rb:5:in `include'
26: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods-deploy/command/deploy.rb:5:in`class:Deploy'
27: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods-deploy/command/deploy.rb:3:in `<class:Command>'
28: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods-deploy/command/deploy.rb:2:in`module:Pod'
29: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods-deploy/command/deploy.rb:1:in `<top (required)>'
30: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
31: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
32: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods-deploy/command.rb:1:in`<top (required)>'
33: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
34: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
35: /Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.9/lib/cocoapods_plugin.rb:5:in `<top (required)>'
36: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
37: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
38: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in`block in safe_activate_and_require'
39: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `each'
40: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in`safe_activate_and_require'
41: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
42: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in`map'
43: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
44: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:326:in`block in run'
45: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `each'
46: /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in`run'
47: /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'

**Comment by petercv** [comment]
If you have any pointers for me I can try if I can fix it.

**Comment by jcampbell05** [comment]
There may be more issues but it looks like for 1.0 this module has changed names or location 

https://github.com/jcampbell05/cocoapods-deploy/blob/master/lib/cocoapods-deploy/command/deploy.rb#L5

**Comment by petercv** [comment]
I think it has been renamed to ProjectDirectory

**Comment by petercv** [comment]
Other things that seem to have changed:
- config.skip_repo_update is not an option anymore (I think they reversed it, by default is doesn't update the repo)
- config.clean= doesn't seem to exist anymore

After commenting those out it start to do something but it can't find any of the podspecs, but I also read something that they are going to change or have changed the Specs directory layout.

**Comment by petercv** [comment]
It actually does look to work pretty reasonable now, except for 1 pod (for a project with lots of pods):

Fetching podspec for `MPFoldTransition` from `https://github.com/CocoaPods/Specs/raw/master/Specs/MPFoldTransition/0.0.1/MPFoldTransition.podspec.json`
The `MPFoldTransition` pod failed to validate due to 1 error:
    - ERROR | license: Invalid file type
    - WARN  | source: Git sources should specify a tag.

You seem to use a class ExternalSources that triggers this error. However a pod install doesn't trigger it so it looks like the deploy command uses more validations?

**Comment by petercv** [comment]
I've moved the 2 config options to the install method:

```
  def install(podfile)
    installer = DeployInstaller.new(config.sandbox, podfile, nil)
    installer.repo_update = false
    installer.clean = false
    installer.install!
  end
```

**Comment by petercv** [comment]
BTW, I only got to see that error after changing some code in the DeployDownloader that handled every error on download as a "Not Found".

**Comment by jcampbell05** [comment]
Hmm I don't think it should do that, it should be as close to the `pod install` behaviour as possible.

**Comment by petercv** [comment]
Looks like it uses some kind of Downloader object:
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/pod_source_installer.rb

**Comment by petercv** [comment]
Any help?

**Comment by petercv** [comment]
BTW, that pod that is giving trouble does have an invalid podspec according to these rules:
http://guides.cocoapods.org/syntax/podspec.html#license

The license should not have an extension rtf, which the pod does have: https://github.com/CocoaPods/Specs/blob/master/Specs/MPFoldTransition/0.0.1/MPFoldTransition.podspec.json

However because the installer does not use the ExternalSources class it does not validate the podspec (might even be a bug in Cocoapods, that it doesn't), so the behavior is different when using the deploy command instead of the install command.

**Comment by petercv** [comment]
I've created a pull request for 1.0 support, which will work as long as the podspecs are valid. I believe it is actually a bug in Cocoapods that it doesn't validate the specs during install (might be an optimization though for non-external sources). However it would still be nice if we could get the same behavior when using deploy vs install. I also think the error message "Not Found" could be improved upon for such edge cases because initially you think that the spec does not exist anymore but in reality it fails validation.

**Comment by petercv** [comment]
I think the current fixes are enough for a 0.0.10 release and we can investigate the validation behavior for a 0.0.11 or something.

**Comment by petercv** [comment]
Pull request is merged which now also contains a workaround for making the podspec downloads more in-line with the normal install behavior so this issue can be closed. Will you make a new release?

**Comment by jcampbell05** [comment]
@petercv Thanks for this, sorry for the slow response. I'll raise these with CocoaPods and file some issues to improve the Feedback for `0.0.11`.

I will make a new release :)

**Comment by jcampbell05** [comment]
@petercv  `0.0.10` should be released now :)

**Comment by petercv** [comment]
@jcampbell05 Thank you!
