### ISSUE TITLE
Compatibility with new cocoapods spec layout

### ISSUE THREAD

**Issue by marcomorain** [jcampbell05/cocoapods-deploy#8]
Cocoapods has changes the layout of the specs repo recently enough, as part of the gitHub performance issues: https://github.com/CocoaPods/CocoaPods/issues/5002

As far as I can tell this has broken `pod deploy`.

Are there any plans to update this project to support the new spec repo format? I'm happy to work on a PR for this if you would like @jcampbell05

**Comment by dodongo** [comment]
Also very interested in this. Currently this plugin is the only way we can have reasonable CI test run times with Cocoapods 1.0+. 

Cocoapods did provide a copy of the old repo at `https://github.com/CocoaPods/Old-Specs.git` but it sounds like new version updates will only be made to `https://github.com/CocoaPods/Specs.git`. 

I would love for this plugin to be part of cocoapods proper, but in the meanwhile it seems like we should be able to change the way we parse the specs repo depending on the source specified in the Podfile.

**Comment by marcomorain** [comment]
From my reading of https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/source/metadata.rb#L41 it looks like the new layout adds 3 levels of folders, each using a character from the MD5 of the pod name, for example, `https://github.com/CocoaPods/Specs/blob/master/Specs/d/a/2/Alamofire/1.1.5/Alamofire.podspec.json`

``` ruby
irb(main):005:0> Digest::MD5.hexdigest('Alamofire')
=> "da208d9cbd49253cc75271c6c269ebce"
```

The first 3 characters of the digest are `da2`, leading to  `/d/a/2/`

**Comment by jcampbell05** [comment]
:) I'm happy for a PR @marcomorain  - I don't have much time for this right now so contributions are appreciated :)

One thing I would love to add is to actually store the path to the podspec in the `lockfile` during the install that way it is future proof :) (This is similar to how Bundler does it I believe)

What do you think ?

**Comment by jcampbell05** [comment]
Started some work on fixing this and I've found a way to inject custom data into the lockfile.

I've also found a way of figuring out which podspec cocoapods decides to use and I now need to work with the Sources manager to then figure out the Repo URL to use

**Comment by dodongo** [comment]
@jcampbell05 Is there a work in progress branch for this? Would love to help if I can.

**Comment by jcampbell05** [comment]
@dodongo  Sure I have my work so far at https://github.com/jcampbell05/cocoapods-deploy/tree/s/NewLayout 
 
It just contains some code that I'm aiming to use so that I can infer the Podspec URL during the resolve step in `pod install` or `pod update`.

Then I hope to store this in the Lockfile using the patch to allow me to write to that.

Then I need to update the `pod deploy` code to use this lockfile infomation and to do thhe usual magic of swapping out the podspec requirements for URL ones.

Then hopefully we can get this released and hopefully in Cocoapods one day!

**Comment by jcampbell05** [comment]
@dodongo Have you worked on this ? I'm going to try and resume what I did.
